<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="templates/**" CopyToPublishDirectory="PreserveNewest" />
    <PackageReference Include="dotnetenv" Version="3.1.1" />
    <PackageReference Include="sixlabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

</Project>
